// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'stat.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

StatValue _$StatValueFromJson(Map<String, dynamic> json) => StatValue(
  $enumDecode(_$StatNameEnumMap, json['name']),
  (json['value'] as num).toDouble(),
  appliesOnlyTo: $enumDecodeNullable(
    _$DamageTypeEnumMap,
    json['appliesOnlyTo'],
  ),
);

Map<String, dynamic> _$StatValueToJson(StatValue instance) => <String, dynamic>{
  'name': _$StatNameEnumMap[instance.name]!,
  'value': instance.value,
  'appliesOnlyTo': _$DamageTypeEnumMap[instance.appliesOnlyTo],
};

const _$StatNameEnumMap = {
  StatName.None: 0,
  StatName.ATK: 1,
  StatName.DEF: 2,
  StatName.HP: 3,
  StatName.FlatATK: 4,
  StatName.ATKPercent: 5,
  StatName.DEFPercent: 6,
  StatName.HPPercent: 7,
  StatName.CritRate: 8,
  StatName.CritDamage: 9,
  StatName.EnergyRegen: 10,
  StatName.HealingBonus: 11,
  StatName.AeroDamage: 12,
  StatName.ElectroDamage: 13,
  StatName.FusionDamage: 14,
  StatName.GlacioDamage: 15,
  StatName.HavocDamage: 16,
  StatName.SpectroDamage: 17,
  StatName.BasicAttackDamage: 18,
  StatName.HeavyAttackDamage: 19,
  StatName.ResonanceDamage: 20,
  StatName.LiberationDamage: 21,
  StatName.CoordinatedAttackDamage: 22,
  StatName.IntroDamage: 23,
  StatName.OutroDamage: 24,
  StatName.EchoDamage: 25,
  StatName.SpectroFrazzleDamage: 26,
  StatName.AeroErosionDamage: 27,
  StatName.GlacioChafeDamage: 28,
  StatName.ElectroFlareDamage: 29,
  StatName.HavocBaneDamage: 30,
  StatName.FusionBurstDamage: 31,
  StatName.GeneralDamage: 32,
  StatName.AeroAmp: 33,
  StatName.ElectroAmp: 34,
  StatName.FusionAmp: 35,
  StatName.GlacioAmp: 36,
  StatName.HavocAmp: 37,
  StatName.SpectroAmp: 38,
  StatName.BasicAttackAmp: 39,
  StatName.HeavyAttackAmp: 40,
  StatName.ResonanceAmp: 41,
  StatName.LiberationAmp: 42,
  StatName.CoordinatedAttackAmp: 43,
  StatName.IntroAmp: 44,
  StatName.OutroAmp: 45,
  StatName.EchoAmp: 46,
  StatName.SpectroFrazzleAmp: 47,
  StatName.AeroErosionAmp: 48,
  StatName.ElectroFlareAmp: 49,
  StatName.GlacioChafeAmp: 50,
  StatName.HavocBaneAmp: 51,
  StatName.FusionBurstAmp: 52,
  StatName.GeneralAmp: 53,
  StatName.AeroRes: 54,
  StatName.ElectroRes: 55,
  StatName.FusionRes: 56,
  StatName.GlacioRes: 57,
  StatName.HavocRes: 58,
  StatName.SpectroRes: 59,
};

const _$DamageTypeEnumMap = {
  DamageType.Raw: 0,
  DamageType.Healing: 1,
  DamageType.Spectro: 2,
  DamageType.Havoc: 3,
  DamageType.Electro: 4,
  DamageType.Aero: 5,
  DamageType.Glacio: 6,
  DamageType.Fusion: 7,
  DamageType.BasicAttack: 8,
  DamageType.HeavyAttack: 9,
  DamageType.Resonance: 10,
  DamageType.Liberation: 11,
  DamageType.SpectroFrazzle: 12,
  DamageType.AeroErosion: 13,
  DamageType.HavocBane: 14,
  DamageType.ElectroFlare: 15,
  DamageType.GlacioChafe: 16,
  DamageType.FusionBurst: 17,
  DamageType.Coordinated: 18,
  DamageType.Intro: 19,
  DamageType.Outro: 20,
  DamageType.Echo: 21,
  DamageType.TuneBreak: 22,
};
